redis:
  hostName: localhost
  port: 6379
  timeout: 5000
  maxIdle: 300
  maxTotal: 1000
  maxWaitMillis: 1000
  minEvictableIdleTimeMillis: 300000
  numTestsPerEvictionRun: 1024
  timeBetweenEvictionRunsMillis: 30000
  testOnBorrow: true
  testWhileIdle: true
  password: 123456

server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

spring:
  application:
    name: service-good
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    type: redis
    cache-names: permission
    redis:
      time-to-live: 300000
      cache-null-values: true
  datasource:
    url: jdbc:mysql://localhost:3306/lsx?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 8000
# 熔断器DashBoard: actuator在boot2.0调整后开关web端点的配置，*代表开启所有
management:
  endpoints:
    web:
      exposure:
        include: "*"

mybatis:
  mapper-locations: classpath:mapping/*.xml
  config-location:  classpath:mybatis-config.xml

single:
  login: false