server:
  port: 8081
eureka:
  instance:
    LeaseExpirationDurationInSeconds: 15
    LeaseRenewalIntervalInSeconds: 5
    hostname: localhost
    prefer-ip-address: true
  server:
    enableSelfPreservation: true
    evictionIntervalTimerInMs: 4000

  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/